#!/bin/bash
 dirname=$(date +%d%b%Y%H%M%S_MysqlBackup_SPECIAL_1)
 mkdir -p /nfsshare/common/${dirname}
 chmod 777 /nfsshare/common/${dirname}

filename=pope-1-3-5-6.lst

for host in `cat $filename`
 do
 ssh $host 'bash -s' << 'EOF'
 echo ${HOSTNAME}
 export GTSENV=090
 gtsenv enter 090
 datestamp=`date +%Y%m%d`
 echo $datestamp
 dirname=$(date +%d%b%Y_MysqlBackup_LOCAL_POPE)

sudo -u xman mysqlbackup --user=root --host=127.0.0.1 --port=19000 -pMcxt7@1234 --with-timestamp --backup-dir=/nfsshare/common/${dirname}/mysqlbackup-$datestamp-${HOSTNAME,,} --backup-image=${HOSTNAME,,}-$datestamp.mbi backup-to-image
 cd /nfsshare/common/${dirname}
 sudo -u xman chmod -R 777 mysqlbackup*

echo "backup taken"
 EOF
 done

for target in `cat target`
 do
 ssh $target 'bash -s' << 'EOF'
 echo ${HOSTNAME}
 export GTSENV=090
 gtsenv enter 090
 datestamp=`date +%Y%m%d`
 echo $datestamp
 dirname=$(date +%d%b%Y_MysqlBackup_LOCAL_POPE)
 sudo -u xman cp -rv /nfsshare/common/${dirname} /atnew/var/
 echo "backup copied"
 EOF
 done
